- tools/rest_api_examples/browser-details
- tools/rest_api_examples/command-modules
- tools/rest_api_examples/dns
- tools/rest_api_examples/export-logs
- tools/rest_api_examples/lib/beef_rest_api.rb
- tools/rest_api_examples/lib/print.rb
- tools/rest_api_examples/lib/string.rb
- tools/rest_api_examples/metasploit
- tools/rest_api_examples/network
- tools/rest_api_examples/webrtc
Some examples for using the RESTful API in Ruby.
I've been using this for testing. Committed in the hope it will be useful to others.
> Add RESTful API example code

- .gitignore
hi guys!
noticed that this directory was missing from the .gitignore file, re-added it in
> added extensions/admin_ui/media/javascript-min/ to .gitignore

- modules/exploits/router/linksys_e2500_csrf/command.js
- modules/exploits/router/linksys_e2500_csrf/config.yaml
- modules/exploits/router/linksys_e2500_csrf/module.rb
- modules/exploits/router/linksys_e2500_dns_hijack/command.js
- modules/exploits/router/linksys_e2500_dns_hijack/config.yaml
- modules/exploits/router/linksys_e2500_dns_hijack/module.rb
- modules/exploits/router/linksys_e2500_shell/command.js
- modules/exploits/router/linksys_e2500_shell/config.yaml
- modules/exploits/router/linksys_e2500_shell/module.rb
I added 3 modules for the Linksys E2500 router.  I have verified this to work on my personal E2500.
> linksys e2500

- modules/social_engineering/pretty_theft/command.js
- modules/social_engineering/pretty_theft/module.rb
Adds IOS styled dialog to the pretty theft module. Also Fixed a 404 for the linkedin logo. Let me know if I need to make any changes. Tested on firefox 39, Safari 8.0.7, Chrome on a mac book pro and chrome and safari on IPad looks like things are working and the dialog looks similar to the one used in the POC. Let me know if there is an issue.
Thanks,
Quentin
> Ios pretty theft

- INSTALL.txt
- README
- README.mkd
- install-beef
https://developer.github.com/changes/2014-04-25-user-content-security/
> URL performance enhanced with user content security

- modules/exploits/wordpress_add_admin/command.js
- modules/exploits/wordpress_add_admin/config.yaml
- modules/exploits/wordpress_add_admin/module.rb
simple Wordpress module to scrape a WP nonce (CSRF token) and use to to automatically create an administrator-level account.
> added a WP module

- README.mkd
> tiny change

- INSTALL.txt
Updated with installation script for Ubuntu based systems. The script may be copied and pasted in full into a terminal session and to run as a single command.
> Update INSTALL.txt with Ubuntu instructions

- arerules/alert.json
- arerules/confirm_close_tab.json
- arerules/man_in_the_browser.json
- arerules/record_snapshots.json
> Four additional ARE rules.

- install-beef
> "it's dependencies" should be "its"

- modules/exploits/farsite_x25_remote_shell/command.js
- modules/exploits/farsite_x25_remote_shell/config.yaml
- modules/exploits/farsite_x25_remote_shell/module.rb
Exploits CVE-2014-7175 and CVE-2014-7173 to get remote code execution through CSRF as an authenticated user.
> FarLinX X25 auth RCE module

- core/main/client/browser.js
Added support to detect the desktop and iOS Chrome browser versions 52 through to 56
> Added support of Chrome 52 to 56

- modules/browser/hooked_domain/deface_web_page/module.rb
- modules/browser/hooked_domain/get_stored_credentials/module.rb
- modules/browser/hooked_domain/site_redirect_iframe/module.rb
- modules/browser/play_sound/module.rb
- modules/exploits/m0n0wall/module.rb
- modules/exploits/nas/freenas_reverse_root_shell_csrf/module.rb
- modules/exploits/pfsense/module.rb
- modules/exploits/wanem_command_execution/module.rb
- modules/exploits/zenoss_3x_command_execution/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop_bypass/module.rb
- modules/social_engineering/clickjacking/module.rb
- modules/social_engineering/fake_flash_update/module.rb
- modules/social_engineering/gmail_phishing/module.rb
- modules/social_engineering/pretty_theft/module.rb
> Updated modules to reference beef_host and beef_port

- modules/exploits/switch/dlink_dgs_1100_port_mirroring/command.js
- modules/exploits/switch/dlink_dgs_1100_port_mirroring/config.yaml
- modules/exploits/switch/dlink_dgs_1100_port_mirroring/module.rb
This module adds a MAC address to the FDB Whitelist.
> Adding DLink DGS 1100 Port Mirroring module

- modules/exploits/switch/dlink_dgs_1100_fdb_whitelist/command.js
- modules/exploits/switch/dlink_dgs_1100_fdb_whitelist/config.yaml
- modules/exploits/switch/dlink_dgs_1100_fdb_whitelist/module.rb
This module adds a MAC address to the FDB Whitelist.
> Adding DLink DGS 1100 FDB Whitelist module

- modules/social_engineering/pretty_theft/command.js
I have improved the title bar behind the texts.
> Improved design

- modules/host/get_internal_ip_webrtc/command.js
* Add Object-RTC implementation that should work in Edge 38.
* Fix issue where WebRTC implementation could report partial results if there are multiple local IP addresses (e.g. multiple network cars, IPv4 & IPv6, ...). In such cases, the results would be reported for each IP address, where they should only be reported once, after all IP addresses have been enumerated.
* All indentation is now 4 spaces.
> Add ORTC, fix WebRTC bug

- extensions/admin_ui/controllers/panel/index.html
I noticed when i put HTML content in "beef-xss/config.yaml" file in Version Field.
And Restart Beef(beef_start.png) and Go to Admin Panel in my browser, then my html interpreter and execute.
This issue occurs bcz of "/beef-xss/extensions/admin_ui/controllers/panel/index.html" in this file insecure code implementetion.
NOW html_escape prevent code execution.
> html_escape prevent code execution .

- extensions/admin_ui/controllers/panel/index.html
> Revert "html_escape prevent code execution ."

- modules/misc/coinhive_miner/command.js
- modules/misc/coinhive_miner/config.yaml
- modules/misc/coinhive_miner/module.rb
This PR adds a [Coinhive JavaScript Miner](https://coinhive.com/) module.
> Add Coinhive Miner module

- core/main/client/dom.js
- modules/misc/cryptoloot_miner/command.js
- modules/misc/cryptoloot_miner/config.yaml
- modules/misc/cryptoloot_miner/module.rb
This integration provides in the misc modules a
crypto-loot miner. It is similar  to coinhive miner
and is inspired by it.
It is designed to be used for test purposes only.
Please, do not use it on people who haven't
given their consent. I.e. no cryptojacking.
In no way the author of this integration are
responsible for the use of it. We also
have no relation to crypto-loot.
> Crypto-Loot miner intergration

- core/main/client/browser.js
Added test for Firefox 58 ("isFF58").
> Added test for Firefox lastest version.

- install
Added ruby and ruby-rdoc to Arch installer in case rdoc isn't installed
> Added ruby and ruby-rdoc to Arch installer

- install
Added detection of alpine linux and required packages
> Alpine linux support

- core/main/rest/handlers/hookedbrowsers.rb
- extensions/admin_ui/api/handler.rb
- extensions/admin_ui/media/javascript/ui/panel/DataGrid.js
- extensions/admin_ui/media/javascript/ui/panel/MainPanel.js
- extensions/admin_ui/media/javascript/ui/panel/tabs/ZombieTabLogs.js
> Add Zombies tab to main panel

- Gemfile
- extensions/network/extension.rb
- extensions/network/rest/network.rb
Remove requirement for `dm-serializer` gem.
Fix #1676
> Remove dm-serialize requirement

- googlef1d5ff5151333109.html
In order to review blacklisting of repo
> Google verify file

- Rakefile
> adding a catch to a possible ruby bug

- Gemfile
This was introduced again and this is just removing it
> remove the rubyracer again

- spec/beef/api/auth_rate_spec.rb
The actual changes that matched the new merges. Should fix one of the dns issues where it doesnt close properly
> the changes made

- .github/ISSUE_TEMPLATE.md
> Bump version to 0.5.0.0

- install
curb fails to build when running bundle install
> Added libcurl4-openssl-dev to apt command. 

- docs/are.js.html
- docs/beef.js.html
- docs/browser.js.html
- docs/browser_cookie.js.html
- docs/browser_popup.js.html
- docs/dom.js.html
- docs/encode_base64.js.html
- docs/encode_json.js.html
- docs/geolocation.js.html
- docs/hardware.js.html
- docs/index.html
- docs/init.js.html
- docs/logger.js.html
- docs/mitb.js.html
- docs/net.js.html
- docs/net_connection.js.html
- docs/net_dns.js.html
- docs/net_local.js.html
- docs/net_portscanner.js.html
- docs/net_requester.js.html
- docs/os.js.html
- docs/session.js.html
- docs/timeout.js.html
- docs/updater.js.html
- docs/webrtc.js.html
- docs/websocket.js.html
Added a few more changes with the updated copyright
> copyright changes to new year

- README.md
Removed the IRC component, its old and not really used.
> updated the ReadMe

- core/main/rest/handlers/admin.rb
- spec/beef/api/auth_rate_spec.rb
- spec/spec_helper.rb
> Fix tests to run in random order

- spec/beef/extensions/adminui_spec.rb
#1845 Fix for Travis CI Failure
> Fixed test to run in random order

- spec/beef/api/auth_rate_spec.rb
Hopefully fixing the Travis CI error
> Set the credentials before test runs

- core/main/ar-migrations/013_create_network_host.rb
- core/main/handlers/browserdetails.rb
- extensions/network/rest/network.rb
- spec/beef/api/auth_rate_spec.rb
- spec/beef/core/main/autorun_engine/autorun_engine_spec.rb
- spec/beef/extensions/network_spec.rb
Bug
Fixing issue #1852 by changing the way network extension REST API searches active record tables.
spec/beef/extensions/network_spec.rb
> fixing issue #1852

- core/main/rest/handlers/hookedbrowsers.rb
This reverts commit 453e4bacabf231a172ed4b8f02fe57d3512ed85b.
Needs to be reviewed
(Bug )
This module is added to ...
revert a pushed comment 
> Revert "related to the change in how ID is used"

- core/main/rest/handlers/hookedbrowsers.rb
- spec/beef/core/main/handlers/browser_details_handler_spec.rb
> update the destroy to destroy all

- modules/network/port_scanner/module.rb
(Bug)
changing it backj and trying to use the network service
> updated to what was changed for the networkservice

- core/main/network_stack/websocket/websocket.rb
> this was a change that needed to be update

- config.yaml
- core/main/handlers/hookedbrowsers.rb
- core/main/handlers/modules/beefjs.rb
> Prevent breaking BeEF due to my split work on hook

- modules/network/sw_port_scanner/command.js
- modules/network/sw_port_scanner/config.yaml
- modules/network/sw_port_scanner/module.rb
> Create sw port scanner

- modules/network/sw_port_scanner/command.js
( module )
This Module is added to ... extend the module and improve it 
Describe what this improves - the response and how accurate the module is
> updated command js for more funcionality

- .travis.yml
core functionality
Adding another test case to the travis.ci
Another test will run for the sake of the docker image
> added a new rvm language for the docker container

- arerules/lan_port_scan.json
- arerules/lan_sw_port_scan.json
extension 
Updated a few ARE rules that had incorrect options 
> fiexed broken values

- .gitignore
- config.yaml
(Bug / module / extension / core functionality / documentation / tests)
> moving these back to defaults

- Gemfile
- spec/beef/extensions/websocket_spec.rb
Updated the websocket tests to test for secure and unsecure websocket servers, and a test to ensure a client can connect to the websocket server.
> Refining websocket tests

- modules/network/fetch_port_scanner/config.yaml
module
This Module is updating the traffic light system, which looks correct
The traffic light system for this module will hopefully work now. 
> Final config with version details

- spec/beef/extensions/websocket_hooked_browser_spec.rb
module
This Module is updating the traffic light system, which looks correct
extensions
> made a new websocket test for the browser

- spec/beef/api/auth_rate_spec.rb
- spec/beef/core/main/handlers/browser_details_handler_spec.rb
Patch
Removing some code unintended to be present in some test files.
ARE config code was copied across into browser handler checking and API authentication rate checking tests. Removed what was unnecessary.
N/A - alterations were to test files.
N/A
> Removed code that was unintended to be copied across in test set-up

- config.yaml
- modules/social_engineering/pretty_theft/command.js
Bug
This feature solves the issues described in issue [1950](https://github.com/beefproject/beef/issues/1950).
As per my description of the issue in the issue itself:
> The `checker` function was trying to access the DOM element with ID `'buttonpress'`. It was trying to access it from the `document.body.lastChild` object instead of directly from `document`. `document.body.lastChild` does not have the .getElementById method, which was causing the error. It works for me locally now.
N/A
N/A
> Pretty Theft Missing Credentials JS Error

- core/main/client/browser.js
> core/main/client/browser.js: Fix array unique function

- core/main/handlers/browserdetails.rb
- extensions/network/rest/network.rb
Bug in Network Map/Host/Services feature.
**Q:** _Please give a brief summary of your feature/fix_
**A:** Re-introducing a patch submitted by @h4sh5 for #1852. It was reverted on the same day it was applied which caused the bug to re-appear. No context was given for the revert. Re-applying the fix locally appear to solve the problem.
**Q:** _Give a technical rundown of what you have changed (if applicable)_
**A:**  Please see #1852 for technical discussion.
**Q:** _Describe your test cases, what you have covered and if there are any use cases that still need addressing._
**A:**  N/A
*If you are adding a new feature that is not easily …
> Fix #1852 - Re-patch of reverted Network Map/Hosts/Services fix

- Gemfile
- extensions/xssrays/rest/xssrays.rb
- spec/support/beef_test.rb
- spec/support/constants.rb
- spec/support/simple_rest_client.rb
*e.g. Tests*
**A:** Start of the Rubocop changes, should be merged after the rubocop gemfile one has been merged. Intending to do smaller iterative after testing, ideally if something goes wrong we have a shortlist of changes to chase down
**A:** Followed the Rubocop guideline where applicable up top 100 changes or so. Left some of the touchy ones till last, focused on the easy fruit first 
**A:**Running automated test cases now 
*If you are adding a new feature that is not …
> Rubocop mergev0.0.1

- install
Added blackPanther OS specific install strings and requires for use
Core Functionality
**A:** Exend support of distros
> Extend distro suppport

- modules/exploits/beefbind/shellcode_sources/msf/instructions.txt
Documentation
Update instructions.txt for shellcode_sources for usage in recent kali linux versions
> Update instructions.txt for recent kali linux

- .github/ISSUE_TEMPLATE.md
Documentation
**A:** Correct typo
**A:** n/a - Changes made in agreement with Standard American English.
> fix(docs): corrects typo in project's ISSUE_TEMPLATE

- extensions/admin_ui/media/javascript/ui/panel/WelcomeTab.js
> AdminUI: Use correct hook file path for bookmarlet hook URL

- core/main/client/browser.js
fix
Bug
**A:** fix FireFix 89.02 document.location.protocol == 'http:' mozGetUserMedia == "undefined"
**A:**
**A:** Open FireFox@89.02,Open an HTTP site, open web devtools, and enter typeof navigator.mozGetUserMedia
> fix FireFix 89.02 document.location.protocol == 'http:' mozGetUserMedia == "undefined"

- .bundle/config
- .github/ISSUE_TEMPLATE.md
- .gitignore
- README.md
- VERSION
- config.yaml
- docs/index.html
- package-lock.json
> Release 0.5.1.0

- INSTALL.txt
Initial issue was around adding instruction to run 'bundle' after git pull, but found out the update-beef does the same, so have updated the install.txt to reflect this
**A:**
**A:**
**A:**
> Usability: updated install.txt to reference the update-beef script

- core/api.rb
> rubocop cleanup

- .github/ISSUE_TEMPLATE.md
- VERSION
- config.yaml
- package-lock.json
- package.json
> version up

- core/api.rb
Rubocop formatting changes broke UI. Reverting for this release
> Hotfix api.rb

- .github/workflows/github_actions.yml
- .github/workflows/main_beef_action.yml
- install
This implements the first stage of github Actions in preparation for all testing to be run through Actions upon any PRs
Don't forget to squash!
> GitHub actions

- .github/workflows/github_actions.yml
Adding the approval process before running BrowserStack tests.
> MAINTAINABILITY: Added approval before code execution.

- scripts/bump-version.sh
Since we're doing so many releases I thought it would be good to create a script to do it for us.
> added script to bump versions for release

- install
Tested on Kali and Ubuntu fresh installs
removed gcc9 from install script as it was causing issues and its purpose is unclear.
#2241 is related issue
> removed gcc9 and libgcc 9 from install

- extensions/admin_ui/handlers/ui.rb
Code Quality, removed a comment based on lack of applicability.
#2288 
**A:** Updates codebase
**A:**Not applicable
**A:** Ran, no test cases needed.
> Code Quality #2288 Removed a comment

- install
Updated the installation script in include missing dependencies espeak and lame
> updated install script to install dependencies

- Dockerfile
**A:** Add a healthcheck in the Dockerfile
**A:** Added instruction HEALTHCHECK in second build stage in Dockerfile.
**A:** None
*If you are adding a new feature that is not easily understood without context, please draft a section to be added to the Wiki below.* : Not necessary.
I don't known which beef http endpoint is better for an healthcheck so i chose the the base path but it would be better to …
> healthcheck

- modules/network/detect_ethereum_ens/command.js
- modules/network/detect_ethereum_ens/config.yaml
- modules/network/detect_ethereum_ens/module.rb
Uses the same technique as the Detect TOR module.
> Detect Ethereum ENS

- modules/network/detect_opennic/command.js
- modules/network/detect_opennic/config.yaml
- modules/network/detect_opennic/module.rb
Uses the same technique as the Detect TOR module.
> Detect OpenNIC DNS

- extensions/admin_ui/api/handler.rb
Evaluate, minify, and file write are all now handled separately.
Minification failure is considered a warning (not fatal).
When running as a user who does not have write permissions to the generated temporary minified JavaScript files, errors are raised and the server starts, but the admin UI JavaScript files have not have been generated.
```
$ ./beef 
[ 6:56:56][*] Browser Exploitation Framework (BeEF) 0.5.4.0
[ 6:56:56]    |   Twit: @beefproject
[ 6:56:56]    |   Site: https://beefproject.com
[ 6:56:56]    |   Blog: http://blog.beefproject.com
[ 6:56:56]    |_  Wiki: https://github.com/beefproject/beef/wiki
[ 6:56:56][*] Project Creator: Wade Alcorn (@WadeAlcorn)
-- migration_context()
-> 0.0170s
[ 6:56:56][*] BeEF is loading. Wait a few seconds...
[ 6:57:00][!] [AdminUI] Error: …
```
> Admin UI: Treat URL route mount failures as fatal

- install
*Extension*
**A: Adding Artix distro under the Arch Linux category for the installer**
> Add Arch based distro 'Artix' for linux installer

- .dockerignore
- Dockerfile
Optimization
**A:** Reduce the size of the Docker image by approximately 72 MB (or 13%).
**A:** It does this by setting the ownership of the beef files in one pass, as well as preventing several files and directories from being included in the (build and) final image.
**A:** -
> feat: optimize Docker image

- Gemfile
- Gemfile.lock
Gem Update
**A:**
Updating the Rack Gem to the last fix
**A:**
**A:**
> Update thin gem

- .github/workflows/github_actions.yml
Maintainability
Currently the tests rely on espeak and lame packages, this will add them to the testing dependencies in the github action
Cannot test this until we have it merged into the master.
> added dependencies and rake tests to workflow

- spec/beef/core/main/configuration_spec.rb
Tests
**A:**
One of the test cases wasn't being correctly loaded. Due to how it was initially implemented it doesn't seem to be correctly raising an error. This will need to be revised in the future. 
**A:**
**A:**
> removing spelling mistake in configuration_spec

- .github/workflows/stale.yml
Adding an auto stale and close to issues, this will help focus on issues that are active and relevant.
> Add bot to help keep the issue backlog clean.

- README.md
Documentation
**A:** In the readme, the link to ruby's project in the installation process doesn't work
**A:** Just the link, now it's working again
**A:** Just to click with and without the change, and check on google the real link
> fix(docs): a redirect fix

- install
Reverts beefproject/beef#2590
Need to run the browserstack-check
> Revert "Add support for the SuSE family in the installer"

- install
Reverts beefproject/beef#2594
Funny name title but i jumped the gun previously.
Looks good
> Revert "Revert "Add support for the SuSE family in the installer""

- extensions/dns_rebinding/api.rb
- extensions/dns_rebinding/config.yaml
- extensions/dns_rebinding/extension.rb
- modules/network/dns_rebinding/command.js
- modules/network/dns_rebinding/config.yaml
- modules/network/dns_rebinding/module.rb
> Add missing copyright headers

- modules/exploits/router/3com_officeconnect_cmd_exec/config.yaml
> 3com_officeconnect_cmd_exec: Fix reference URL

- install
…90)" (#2594)"
This reverts commit dc9e41c55a467e34d2f494aacfbc95b230a6df56.
*Core Functionality*
**A:*updated code in install file will now applicable for arch distro*
**A:*i added code snippet for garuda distribution*
**A:**
> Installation problem solved in garuda linux

- extensions/qrcode/qrcode.rb
- modules/social_engineering/clickjacking/command.js
> Replace URI.escape with URI::Parser.new.escape

- Dockerfile
Infrastructure
**A:** Rewrote Dockerfile.
**A:** New docker image is now based on debian (this should improve future glibc compatibility issues), made ports settable during `docker build`, removed what seemed to be redundant dependencies (net saving approx 100 MB), minimized layers and applied other [Dockerfile Best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), and did some formatting to make it readable.
**A:** Not much. The image can be built, I can start the webserver, get hooked and shoot off some basic …
> Rework Dockerfile

- extensions/events/handler.rb
> BeEF::Extension:::Events: Add error handling to event parsing

- config.yaml
- core/main/handlers/hookedbrowsers.rb
> config: add comments for public connect-back settings

- install
> install: update installer to support Ruby 3.x

- core/main/autorun_engine/engine.rb
- core/main/autorun_engine/parser.rb
- core/main/autorun_engine/rule_loader.rb
b308d8c643946bf8219f2c3c1d91e253b52ce3de - Fixes #1968
4555b55844b84a3ef91078b0b70650c9bc6f0acc - Fixes #2103
> AutorunEngine: RuleLoader: Skip enabled rule file if rule is already in database

- .github/workflows/github_actions.yml
spelling error
**A:**
**A:**
**A:**
> Update github_actions.yml for spelling error

- .github/workflows/github_actions.yml
Tests
**A:** Update GitHub workflow for Browserstack testing
**A:** Update GitHub actions workflow file to use the latest version of checkout action and ruby version from .ruby-version file. This should allow to test the latest sqlite and activerecord upgrades.
**A:** As workflow is running from the master branch, it needs to be merged to confirm it's working as expected. This does not impact the core functionality, just the automated testing.
*If you are adding a new feature …
> Update GitHub workflow for Browserstack testing

- .github/workflows/dependabot-auto-merge.yml
Automation
**A:** Automate Dependabot merging given Browserstack tests pass (#3207)
**A:** Created new yml workflow file, which should automatically merge dependabot patch and minor updates.
**A:** To test it I will monitor for PRs coming from dependabot and see if automation merges patch and minor updates but not major.
> Automate dependabot merging

- .github/workflows/dependabot-auto-merge.yml
Bug
**A:** main branch was specified as the target branch instead of master on the initial dependabot auto merge yml.
**A:**
**A:** Will be able to test when it's merged and dependabot raises new PRs.
> Update merge target branch for dependabot

- .github/workflows/dependabot-auto-merge.yml
Bug
**A:** Add enable auto merge part into dependabot auto merge yml.
**A:** It seems like by default the auto merge is disabled, thus added code to enable it on a given PR before merging. 
**A:** Testing once it's merged to master
> Add enable auto merge to dependabot yml

- .github/workflows/dependabot-auto-merge.yml
> Revert "Add enable auto merge to dependabot yml"

- README.md
*Documentation*
**A:** Update Discord invite code in README.md file
> Update Discord invite code
