beefproject/beef

- modules/network/ADC/f5_bigip_cookie_disclosure/command.js
- modules/network/ADC/f5_bigip_cookie_disclosure/config.yaml
- modules/network/ADC/f5_bigip_cookie_disclosure/module.rb
- modules/network/ADC/f5_bigip_cookie_stealing/command.js
- modules/network/ADC/f5_bigip_cookie_stealing/config.yaml
- modules/network/ADC/f5_bigip_cookie_stealing/module.rb
This pull request contains new directory for Application Delivery Controllers (ADC) modules and two modules for BigIP systems. It is known that ADCs are widely used for load balancing, applications delivery and firewalling on application layer. It is suggested to develop another modules for F5 BigIP, Citrix NetScaler, etc. that can be used during web aplications and browsers pentesting.
Authors: 
* Denis Kolegov (@dnkolegov)
* Oleg Broslavsky (@yalegko)
* Nikita Oleksov (@neoleksov)
Links:
[OWASP Secure Configuration Guide Project] (https://www.owasp.org/index.php/SCG_D_BIGIP)
[Overview of BIG-IP persistence cookie encoding] (https://support.f5.com/kb/en-us/solutions/public/6000/900/sol6917.html)
> Add first modules for BigIP systems

- modules/exploits/kemp_command_execution/command.js
- modules/exploits/kemp_command_execution/config.yaml
- modules/exploits/kemp_command_execution/module.rb
This is a new module for BeEF to exploit a RCE vulnerability in Kemp
Load Master load balancer. More information on this blog post:
http://blog.malerisch.net/2015/04/playing-with-kemp-load-master.html
> Kemp Load Master RCE - BeEF module

- tools/csrf_to_beef/csrf_to_beef
- tools/csrf_to_beef/lib/module.rb
- tools/csrf_to_beef/lib/output.rb
csrf_to_beef tool now accepts --url URL as input
```
CSRF to BeEF module tool v0.0.3, create a BeEF CSRF module from file or URL.
Usage: ./csrf_to_beef [options] --name <NAME>  <--url=URL|--file=FILE>
Options:
-h, --help            Help
-v, --verbose         Verbose output
-n, --name NAME       BeEF module name
-u, --url URL         CSRF URL
-m, --method METHOD   CSRF HTTP method (GET/POST)
-d, --post-data DATA  CSRF HTTP POST data
-f, --file FILE       Burp CSRF PoC file
Example Usage:
CSRF URL:
./csrf_to_beef --name "example csrf" --url "http://example.com/index.html?param=value"
CSRF URL (POST):
./csrf_to_beef --name "example csrf" --url "http://example.com/index.html" --method POST --post-data "param1=value&param2=value"
Burp Suite CSRF PoC file:
./csrf_to_beef --name "example csrf" …
```
> Update csrf_to_beef tool 

- extensions/social_engineering/powershell/powershell_payload
- modules/social_engineering/hta_powershell/command.js
I was trying to get the hta_powershell attack working with phishing-frenzy and kept running into an error when the target would attempt to get the initial stager.
`<...snip...> Unknown request to /INITM #"Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)", "Host"=>"XXX.XXX.XXX.XXX:443", "Connection"=>"Keep-Alive"}, @auto_cl=true, @state=3, @transfer_chunked=false, @inside_chunk=false, @bufq="", @body="", @method="GET", @raw_uri="/INITM", @uri_parts={"QueryString"=>{}, "Resource"=>"/INITM"}, @proto="1.1", @chunk_min_size=1, @chunk_max_size=10, @uri_encode_mode="hex-normal", <...snip...> `
As noted in mattifestation/PowerSploit#65, /INITM is not a supported URI, as meterpreter now uses a checksum URI that matches the :init_native checksum value.
Merging the changes in …
> Fixed hta_powershell module so that it can establish a meterpreter session.

- beef
I think this is likely not intended functionality but an oversight. Anyhow, I keep configs in my home directory so this change allows my to load these without a bunch of `../`
> Config file should not be relevant to beef install dir

- core/ruby/security.rb
- extensions/dns_rebinding/api.rb
- extensions/dns_rebinding/config.yaml
- extensions/dns_rebinding/dns_rebinding.rb
- extensions/dns_rebinding/extension.rb
- extensions/dns_rebinding/views/index.html
- modules/network/dns_rebinding/README.md
- modules/network/dns_rebinding/command.js
- modules/network/dns_rebinding/config.yaml
- modules/network/dns_rebinding/module.rb
This is implementation of DNS Rebinding attack. There is readme in module/network/dns_rebinding.
Attack tested on my machine in browser Opera 27 and Chrome 40.
It will be great if someone test it besides me.
There is one important thing. Attack uses iptables to block client. Iptables calls through system() and need sudo, that isn't good. system() is patched in BeEF. Now i am thinking about how can we block client without Iptables, but I can't invent way to do it yet. If someone sugget good way it will be great!
> Implementation of DNS Rebinding attack - module and extension

- core/main/client/lib/jquery.blockUI.js
- core/main/handlers/modules/beefjs.rb
- modules/misc/blockui/command.js
- modules/misc/blockui/config.yaml
- modules/misc/blockui/module.rb
- modules/misc/unblockui/command.js
- modules/misc/unblockui/config.yaml
- modules/misc/unblockui/module.rb
This PR adds [jQuery BlockUI plugin](https://github.com/malsup/blockui/) JavaScript library (20KB) to the hook.
BlockUI lets us create pretty modal dialogs.
Tested on:
* Firefox 31 on Linux
* Firefox 40 on Windows
* Chrome 44 on Windows
* Safari 5 on Windows
* Internet Explorer 8 on Windows
* Safari 4 on Android
* Firefox 40 on Android
* Chrome 44 on Android
> Add jQuery BlockUI plugin to hook

- core/main/client/browser.js
Modified core/main/client/browser.js's beef.browser.javaEnabled to return the result of calling Window.navigator.javaEnabled instead of only returning false.
This method should be compatible with all major browsers:
> Add logic for beef.browser.javaEnabled function

- modules/host/get_internal_ip_webrtc/command.js
This update adds support for IPv6 to the RTCPeerConnection revealing internal IPv6 addresses as well.
> Add IPv6 Support to get_internal_ip_webrtc command

- core/main/autorun_engine/engine.rb
The correct is to check if the *rule.browser* has the tag "ALL", not if the browser was identified as "ALL", which of course never happen.
Before this fix, using "ALL" in a ARE rule makes it be never called.
> Fix "ALL" comparison for browser and os

- core/loader.rb
Fixes #1216 by loading the 'optparse' library in ```core/loader.rb```.
> Update loader.rb to include optparse

- core/main/client/lib/webrtcadapter.js
- core/main/client/mitb.js
- modules/browser/detect_extensions/command.js
- modules/persistence/confirm_close_tab/command.js
- modules/persistence/confirm_close_tab/module.rb
Added couple of bug fixes in MITB module and some additional options in Persistence pop-under, also some minor fixes and improvements.
> Bug fixes + additional options

- Gemfile
- Gemfile.lock
- arerules/win_fake_malware.json
- modules/social_engineering/text_to_voice/command.js
- modules/social_engineering/text_to_voice/config.yaml
- modules/social_engineering/text_to_voice/module.rb
Fix #116
This PR adds a Text to Voice module. This module makes use of the espeak-ruby gem (which uses eSpeak for text-to-voice and Lame for MP3 encoding) to provide text-to-voice capabilities to BeEF.
An ARE rule is also provided: Windows Fake Malware. This ruleset makes use of the Fake Notification module and BlockUI in combination with the Text to Voice module in an attempt to coerce the user into running an executable.
> Add Text to Voice module

- modules/persistence/hijack_opener/command.js
- modules/persistence/hijack_opener/config.yaml
- modules/persistence/hijack_opener/module.rb
This module abuses `window.location.opener` to hijack the opening window, replacing it with a BeEF hook and 100% * 100% iframe containing the referring web page.
Note that the iframe will be blank if the origin makes use of a restrictive `X-Frame-Origin directive`.
This attack will only work if the opener did not make use of the `noopener` and `noreferrer` directives. Refer to [Target="_blank" - the most underestimated vulnerability ever](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/) for more information.
This module only works on Firefox for the moment out of sheer laziness, as only Firefox supports loading script contact from `data` URLs. There's no reason this module couldn't be updated to work with all modern browsers by dynamically …
> Add Hijack Opener module

- modules/persistence/hijack_opener/command.js
- modules/persistence/hijack_opener/config.yaml
- modules/persistence/hijack_opener/module.rb
Update Hijack Opener Window module to use server-side iframe loader. Now works on most modern browsers (not Opera).
Tested (working):
* Firefox 49 on Windows
* Chrome 49 on Windows
* IE 8 on Windows
* Safari 5 on Windows
* SeaMonkey 2.39 on Windows
* Iceweasel 31 on Linux
Tested (not working):
* Opera 11 on Windows (returns `Security error: attempted to write protected variable`)
> Update Hijack Opener Window module to use server-side iframe loader

- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_dynamic_token/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_dynamic_token/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_dynamic_token/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_password/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_password/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_password/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_static_token/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_static_token/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_admin_static_token/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_file_disclosure/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_file_disclosure/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_file_disclosure/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_migrate_hook/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_migrate_hook/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_migrate_hook/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop_bypass/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop_bypass/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop_bypass/module.rb
- modules/exploits/zeroshell/zeroshell_2_0rc2_reverse_shell_csrf_sop_bypass/x.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_scanner/command.js
- modules/exploits/zeroshell/zeroshell_2_0rc2_scanner/config.yaml
- modules/exploits/zeroshell/zeroshell_2_0rc2_scanner/module.rb
- modules/network/internal_network_fingerprinting/command.js
Adding ZeroShell 2.0RC2 modules to BeEF
(RCE / Password and token disclosure) - Update Internal Network fingerprinting
To see a demonstration of these modules, please check this private video here : https://www.youtube.com/watch?v=6Jk0QyPG3fU
These modules are based on my previous advisory here : https://packetstormsecurity.com/files/122799/ZeroShell-2.0RC2-File-Disclosure-Command-Execution.html
> Adding ZeroShell 2.0RC2 modules to BeEF

- modules/host/detect_antivirus/command.js
- modules/host/detect_antivirus/config.yaml
Avast Safe Zone is the antivirus browser installed with Avast. This commit adds the detection for this UA:
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 ASW/1.51.2220.62`
Looking for `ASW /` in the ua string.
> add Avast (ASW) detection to the detect_av module

- arerules/get_cookie.json
- modules/browser/hooked_domain/get_cookie/command.js
Updated the Get_cookie ARE module to return a status. Tested on Ubuntu 16.04 x64.
Side note - I added in debugging strings but I could not get those to display even though I used -v and turned debugging on through config.yaml.
> Get cookie ARE status update

- modules/persistence/invisible_htmlfile_activex/command.js
- modules/persistence/invisible_htmlfile_activex/config.yaml
- modules/persistence/invisible_htmlfile_activex/module.rb
This PR adds a persistence module for Internet Explorer using a `HtmlFile` ActiveX control.
More information: https://www.brokenbrowser.com/zombie-alert/
Fix #1363
> Add Invisible HTMLFile ActiveX persistence module

- modules/exploits/pfsense/pfsense_2.3.2_reverse_root_shell_csrf/command.js
- modules/exploits/pfsense/pfsense_2.3.2_reverse_root_shell_csrf/config.yaml
- modules/exploits/pfsense/pfsense_2.3.2_reverse_root_shell_csrf/module.rb
- modules/exploits/pfsense/pfsense_2.3.2_reverse_root_shell_csrf/x.js
- modules/network/internal_network_fingerprinting/command.js
pfSense 2.3.3 just released with a patch for my latest exploit (Reverse root shell in pfSense).
So I released this BeEF module targeting pfSense <= 2.3.2.
Demonstration video : https://www.youtube.com/watch?v=IWtf6LlfP_c
> Add pfSense <= 2.3.2 Reverse root shell via CSRF/XSS exploit module

- modules/exploits/switch/dlink_dgs_1100_device_reset/command.js
- modules/exploits/switch/dlink_dgs_1100_device_reset/config.yaml
- modules/exploits/switch/dlink_dgs_1100_device_reset/module.rb
Module will reset all settings on a switch except for the IP address.  In the process, it resets the default credentials, allowing a known password to be set.  The hooked browser must be authenticated to the switch for this module to work.
> Adding DLink DGS 1100 Switch Device Reset CSRF Module

- extensions/proxy/proxy.rb
Beef automatically calculates and inserts a Content-Length header when
sending proxy responses. If the Transfer-Encoding header is not
stripped, many browsers treat this as a Content-Length of 0, thus
rendering an empty body.
This fixes Issue #1048
> Omit Transfer-Encoding header in proxy responses

- modules/persistence/jsonp_service_worker/command.js
- modules/persistence/jsonp_service_worker/config.yaml
- modules/persistence/jsonp_service_worker/module.rb
Idea extracted from https://c0nradsc0rner.wordpress.com/2016/06/17/xss-persistence-using-jsonp-and-serviceworkers/
The website where user has been exploited through a XSS, if exposes an unfiltered JSONP callback, can be persistently hooked through service worker onfetch event (Chrome only).
> Persistence through unfiltered JSONP callback and service worker

- modules/persistence/jsonp_service_worker/command.js
For JSONP persistence module. The gsub! against the ruby variable subs the chars, but the method returns nil. Changed to a simple gsub, so it returns the expected string.
> JSONP tempBody variable working again

- Gemfile
A newer version of therubyracer is required on Ruby 2.4
> fix gemfile; closes #1428

- beef
Two commits - here.
Older generates a random phrase if default user and password is in use.
Second commit - slightly more robust testing of default phrase to catch `password` or `beef1`.
> #1444 high risk

- extensions/notifications/channels/pushover.rb
- extensions/notifications/config.yaml
- extensions/notifications/notifications.rb
This adds [Pushover](https://pushover.net/) support as a notification channel to BeEF.
To test, edit the `config.yaml` for your beef project, and ensure the following is present:
```yaml
extension:
notifications:
enable: true
```
In `extensions/notifications/config.yaml`, enable the `pushover` module, replace `pushover_user_key` with your pushover user api key, and replace `pushover_api_key` with the app token you created for BeEF in the Pushover console.
Finally, install the `rushover` gem with `gem install 'rushover'`
> Add Pushover notification channel

- Gemfile
- extensions/notifications/channels/slack_workspace.rb
- extensions/notifications/config.yaml
- extensions/notifications/notifications.rb
This PR adds Slack notifications to the Notifications extension.
> Add Slack notifications to Notifications extension

- extensions/notifications/channels/pushover.rb
Adds error notifications to the recently added pushover channel.
A sample error notification in the console will look like:
```
[*] BeEF server started (press control+c to stop)
[!] [Notifications] Pushover notification initialization failed: 'Failed to open TCP connection to api.pushover.net:443 (Connection refused - connect(2) for "api.pushover.net" port 443)'
```
> Add error messages to pushover notification channel

- modules/network/identify_lan_subnets/command.js
I've removed an erroneous `);`
> Fixing syntax error in identify_lan_subnets

- core/main/client/browser.js
A Fix for #1343 browser_type redundant null values
Check for null on CriOS matches in `isC*iOS()`
Restored quick patch in  34967f61 
Quick added Chrome version 63 for iOS, so that the browser was detected.
> FIX 1343 browser_type redundant null values

- extensions/social_engineering/powershell/bind_powershell.rb
bind_powershell module has http protocol hard coded, preventing powershell_hta from being able to download the payload image from a beef instance which uses SSL. Change pulls protocol from the config file similar to other modules.
> add https support to bind_powershell

- install
The tricky part is that on OpenBSD, there might be multiple
Ruby versions available in parallel. They are, and the binaries
using each of thse version, suffixed with the version number.
Therefore add a global variable RUBYSUFFIX default to empty,
Once the script detects OpenBSD, it enumerates the potentially
valid RUBYSUFFIX variables, from newer to older, until it finds one,
setting the RUBYSUFFIX apropriately. Then the rest of the script
uses the RUBYSUFFIX all over the place, where ruby commands
are used.
the script itself still requires bash, and has to be started with
bash install
as well as beef has to be started with i.e.
ruby24 beef
> Add support to install script to install BeEF on OpenBSD.

- install
Addresses part of #1477.
Uses homebrew (`brew`) to install dependencies. 
Checks if homebrew is installed, if not exits.
If homebrew is present runs `brew update` to get the latest formula then runs `brew install ${package}`.
> Add install_mac logic

- modules/persistence/jsonp_service_worker/command.js
The original module had a JS error, plus the HTML body passed as an option was being rendered escaped. This addresses both of the issues
> Fix JSONP persistence module

- install
Added support for Arch Linux in ./install for an automated installation. Installs dependencies (works on my machine, not sure if there are some I missed...)
Assumes that `ruby` is already installed and in the $PATH.
> Added Arch installer

- modules/browser/webcam/command.js
Return Base64 encoded image url is not valid and regex to check base64 encoded image was reject that and show as a plain text. I fix it with a little change.
> Fix Webcam(Adobe Flash) incorrect base64 data image

- Gemfile
- README.md
therubyracer has long been unmaintained which is causing both security and build
issues to go unfixed. As beef depends on it only to provide a JS runtime for
execjs, we can drop it and require users to install Node.js. execjs
automatically finds the node binary and uses it as a JS runtime.
This fixes #1478, #1045, #1046, #1249, #1374, #1377, #1395, #1396, #1428, #1429
This also fixes #1433, #1502, #1504, #1540, #1545, #1547
> Remove the dependency on therubyracer

- modules/browser/hooked_domain/rickroll/command.js
The original YouTube video did not allow embedding. It has been fixed.
> RickRoll module fix

- install
Without package "ruby-dev", I got this error on my Kali Linux:
Building native extensions. This could take a while...
ERROR:  Error installing json:
ERROR: Failed to build gem native extension.
current directory: /var/lib/gems/2.5.0/gems/json-1.8.6/ext/json/ext/generator
/usr/bin/ruby2.5 -r ./siteconf20190117-11443-w5znm6.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
> Added ruby-dev package for Debian and Kali

- Gemfile
- beef
- config.yaml
- core/core.rb
- core/main/geoip.rb
- core/main/handlers/browserdetails.rb
- extensions/admin_ui/controllers/modules/modules.rb
Update the GeoIP geolocation functionality.
* Uses the MaxMind GeoLite2 database and official `maxmind-db` Ruby gem, replacing the `geoip` gem which relied upon the old MaxMind GeoLite databases which are no longer supported - Fix #1668 
* Moves the GeoIP functionality out of `BrowserDetails` and into its own `Singleton` class as part of the core API - `BeEF::Core::GeoIp`.
* Enables GeoIP by default. Note that the GeoIP database is not distributed with BeEF.
> Update GeoIP to use MaxMind GeoLite2

- core/main/client/timeout.js
May or may not break the ARE.
The `setTimeout` call for `beef_init` is required for hooking in instances where the script is loaded after page load. This is possible is several scenarios, such as DOM XSS, using the `Hook Me!` bookmarklet, and hooking via XSS in Flash objects (probably - untested).
> Uncomment beef_init

- extensions/admin_ui/media/javascript/ui/panel/tabs/ZombieTabXssRays.js
- extensions/xssrays/api.rb
- extensions/xssrays/controllers/xssrays.rb
- extensions/xssrays/extension.rb
- extensions/xssrays/handler.rb
- extensions/xssrays/rest/xssrays.rb
- tools/rest_api_examples/lib/beef_rest_api.rb
- tools/rest_api_examples/xssrays
* Adds API endpoints:
* `/api/xssrays/rays`
* `/api/xssrays/scans`
* Adds `xssrays` REST example usage script
* Fixes some issues with XssRays UI
* Removes the `zombies.json` mount for XssRays logs
* UI now uses the REST API to retrieve the XssRays logs
Part of #1682
> Add XssRays API endpoints

- core/bootstrap.rb
- core/filters/browser.rb
- core/main/client/browser.js
- core/main/client/os.js
- core/main/handlers/browserdetails.rb
- core/main/models/browserdetails.rb
- core/main/network_stack/websocket/websocket.rb
- core/main/rest/api.rb
- core/main/rest/handlers/autorun_engine.rb
- core/main/rest/handlers/browserdetails.rb
- core/main/rest/handlers/hookedbrowsers.rb
- extensions/admin_ui/api/handler.rb
- extensions/admin_ui/controllers/modules/modules.rb
- extensions/admin_ui/media/javascript/ui/panel/BrowserDetailsDataGrid.js
- extensions/admin_ui/media/javascript/ui/panel/tabs/ZombieTabDetails.js
- modules/browser/detect_activex/module.rb
- modules/browser/detect_vlc/module.rb
- modules/browser/detect_wmp/module.rb
- modules/browser/spyder_eye/module.rb
- modules/host/get_internal_ip_webrtc/module.rb
- tools/rest_api_examples/browser-details
- tools/rest_api_examples/lib/beef_rest_api.rb
Updates the usage of the `BrowserDetails` module throughout the framework to use textual OID-style key/value data.
Update the `Details` tab in the AdminUI to render the data as key/value pairs.
Fixes #581
> Update BrowserDetails to store textual OID-style key/value data

- install
I just installed BeEF in Arch Linux and it returned an error saying it couldn't detect my Linux distro, then I noticed this line:
`DISTRO_ID=$(cat /etc/os-release | grep  ID= | cut -d= -f2-)`
it was returning the next output:
`arch
rolling`
It was getting the value of ID and BUILD_ID, so I excluded BUILD_ID to get just the ID value:
`cat /etc/os-release | grep  ID= | grep -v "BUILD" | cut -d= -f2-`
> Excluding BUILD_ID while getting the distro ID

- beef
- config.yaml
- core/loader.rb
- core/logger.rb
- core/main/configuration.rb
- core/main/network_stack/websocket/websocket.rb
- core/main/server.rb
- core/ruby/print.rb
- extensions/admin_ui/api/handler.rb
- extensions/admin_ui/classes/httpcontroller.rb
- extensions/console/extension.rb
- extensions/evasion/evasion.rb
- extensions/metasploit/api.rb
- extensions/metasploit/rpcclient.rb
Adds logging using Ruby `logger`.
Logs to `~/.neef/beef.log` by default. Default log level is `Logger::WARN`.
Setting `debug: true` in `config.yaml` changes log level to `Logger::DEBUG`.
This PR also makes a couple of changes to the configuration file loading, specifically the addition of some very simplistic config validation in `BeEF::Core::Configuration.instance.validate`, and moves some error handling related to the `Console` extension out of the main `beef` file and into the `Console` extension.
This PR also moves the default database path to `~/.beef/beef.db`. This may or may not be a good idea.
> Add logger - Fixes #1698

- extensions/proxy/proxy.rb
I noticed proxying wasn't working with a site that returns all it's headers in lowercase. Although it would be preferable if the application returned the conventional-cased headers, the HTTP 1.1 RFC specifically [calls out](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) headers as case-insensitive. This change allowed me to use the proxy with the site.
> proxy:ignore case when ignoring headers

- core/main/client/geolocation.js
Changed url from http to https, as it was getting blocked by Chrome in https sites. Added dataType "json", parseJSON not required so got rid of it. Changed format from json to jsonv2, as OSM was not sending a content type header in "json" but does send an "application/json" header in jsonv2, this fixes Cross Origin Read Blocking in Chrome (https://www.chromestatus.com/feature/5629709824032768).
> Fixed OpenStreetMap

- Gemfile
- test/common/beef_test.rb
- test/integration/tc_login.rb
- test/integration/ts_integration.rb
The existing selenium gem is old and has it's own dependencies which are no longer available.
This pull updates the test-cases to use the selenium-webdriver gem, which is currently maintained.
Performing these updates allows a larger proportion of testcases to be successfully performed on CentOS 7.6 and Ubuntu 19.04
> Update selenium dependency to selenium-webdriver

- modules/misc/wordpress/add_user/command.js
- modules/misc/wordpress/add_user/config.yaml
- modules/misc/wordpress/add_user/module.rb
- modules/misc/wordpress/current_user_info/command.js
- modules/misc/wordpress/current_user_info/config.yaml
- modules/misc/wordpress/current_user_info/module.rb
- modules/misc/wordpress/upload_rce_plugin/beefbind.php
- modules/misc/wordpress/upload_rce_plugin/command.js
- modules/misc/wordpress/upload_rce_plugin/config.yaml
- modules/misc/wordpress/upload_rce_plugin/module.rb
- modules/misc/wordpress/wordpress_command.rb
- modules/misc/wordpress/wp.js
- Fixes https://github.com/beefproject/beef/issues/1782, and improves the module
- Improves the existing `misc/wordpress_post_auth_rce` module
- Adds a `misc/wordpress_current_user_info` module
- Wordpress modules give more info when they fails (such as username already used when adding a user, error when uploading the plugin and so on), and have the proper 'Success' / 'Error' status
Questions:
- How do I create a Wordpress category in the module folder ? creating a `module/wordpress` folder is not enough by the looks of it
- Do I delete the previous modules (`modules/exploits/wordpress_add_admin` and `modules/misc/wordpress_post_auth_rce`) ?
> WordPress Fixes and Improvements

- .gitignore
- spec/beef/api/auth_rate_spec.rb
auth_rate_spec.rb sometimes fails due to the the original apis.reverse call doesn't actually reverse the apis list (the changes are not stored.)
by changing it to 
```rb
apis = apis.reverse if (apis[0].is_pass?(BEEF_PASSWD))
```
this bug is fixed.
Also added beef.log and .byebug_history into the gitignore file to prevent data leaks
> Fixing random fails in auth_rate_spec.rb

- .bundle/config
- core/main/ar-migrations/011_create_web_cloner.rb
- core/main/ar-migrations/012_create_mass_mailer.rb
- core/main/ar-migrations/015_create_http.rb
- core/main/ar-migrations/016_create_rtc_status.rb
- core/main/ar-migrations/017_create_rtc_manage.rb
- core/main/ar-migrations/018_create_rtc_signal.rb
- core/main/ar-migrations/019_create_rtc_module_status.rb
- core/main/ar-migrations/020_create_xssrays_detail.rb
- core/main/ar-migrations/022_create_ipec_exploit.rb
- core/main/ar-migrations/023_create_ipec_exploit_run.rb
- core/main/ar-migrations/024_create_autoloader.rb
- core/main/ar-migrations/025_create_xssrays_scan.rb
Changing some of the table names
> Active record fix

- Rakefile
- extensions/metasploit/api.rb
Switched to using yaml.safe_load as yaml.load is considered insecure.
> Replaced yaml.load with yaml.safe_load

- core/main/crypto.rb
https://github.com/beefproject/beef/issues/1805
> Use SecureRandom

- config.yaml
- core/bootstrap.rb
- core/main/router/error_responses.rb
- core/main/router/router.rb
- extensions/admin_ui/classes/httpcontroller.rb
- extensions/admin_ui/controllers/authentication/authentication.rb
- spec/beef/extensions/adminui_spec.rb
Adds the fix for spoofing the Admin UI, includes some minor changes around how 404 error responses are accessed and includes tests.
> Fix broken admin ui access

- core/main/network_stack/assethandler.rb
Untested but seems like a good idea.
> Add error handling and minor code cleanup

- .travis.yml
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
> Add Ruby 2.7.0 to travis.yml

- core/main/handlers/browserdetails.rb
Had this diff lying around for a while. I think these are the last of the `BrowserDetails` which aren't OID style.
The host IP address seems more suited to the `network` object than the `host` object, as we the IP address more than likely represents an intermediary router IP address.
> Use OID-style key/value data for BrowserDetails network details

- extensions/admin_ui/controllers/modules/modules.rb
Bug
There was a bug in the build_recursive_tree function, which was triggered when you
tried to generate folders which only contained subfolders (without modules).
> Fixed build_recursive_tree()

- core/main/rest/handlers/hookedbrowsers.rb
Fixes a bug where adding a longer timeout for websocket polls causes the browser to show as offline in the ui panel.
> Changed how websocket hooked browsers time out

- modules/network/sw_port_scanner/command.js
module /
make the module run faster and be more accurate
> updated command.js for sw_network_proxy

- install
install script
The install script now checks for Ruby package managers and will not install ruby if they are present.
Ruby version check takes package manager into account now
Added 'sudo' to the gem install to handle newer Kali 2020 where user is no longer root
Checks whether rvm or rbenv are being used. Only installs ruby if package manager is NOT present
I don't believe changes need to be made to wiki
> sudo for gem install, ruby package manager check

- core/main/client/browser.js
- docs/browser.js.html
- extensions/events/handler.rb
- modules/browser/browser_fingerprinting/command.js
- modules/browser/hooked_domain/ajax_fingerprint/command.js
- modules/browser/hooked_domain/get_form_values/command.js
Bug
This PR removes a bug that was described in issue [1909](https://github.com/beefproject/beef/issues/1909).
As per my description of the issue in the issue itself:
> As suggested by **bcoles** I did a bit of digging and found a cleaner jQuery alternative to address the problem that the `Array.prototype.unique` function was solving. 
```javascript
function unique(array) {
return $.grep(array, function(el, index) {
return index === $.inArray(el, array);
});
}
```
> The code snippet shared above by **l0kihardt** should now result in the expected behaviour:
```javascript
let a = [{}, {}, {}];
for(i in a){
console.log(i);
}
// OUTPUT
0 
1
2
```
Tests are passing and I haven't noticed any other issues/bugs caused by …
> Replaced Array.prototype.unique with a cleaner jQuery equivalent

- extensions/admin_ui/media/javascript/ui/panel/zombiesTreeList.js
Hi, noticed there is a little issue that makes zombies disappear in the console.
https://github.com/beefproject/beef/issues/1712
The issue has been closed, but other people are still facing it.
Bug in the Admin interface
The issue is simple, BeeF doesn't show hooked browser, but it's still logging them, as observable by the image below:
From the web console, it's easy to see that the issue is presenting at the presentation layer (it's a JavaScript file: web_ui_all.js):
The code in web_ui_all.js is minified, and the error triggers in the following snippet (notice the same error appears twice in the same file):
```javascript
((c += " <img width='13px' height='13px' class='zombie-tree-icon' src='/ui/media/images/icons/country-squared/" + escape(e.country_code.toLowerCase()) + ".svg' /> "), …
```
> Fix country_code is null

- extensions/xssrays/rest/xssrays.rb
*e.g. Bug*
**A:** related to #1983, when running XSSRays it fails in a catch for an internal server error. This is due to Ruby trickery that my simple fix resolves. There is likely to be more errors related to this that ill chase down later, however this one resolves this part of it and the specific ticket.
**A:**  A fun fact about using the where function is that it returns  ActiveRecord::Relation which basically acts like an array. Since its using that to find the record we have to go into it similar to how we would go into a hash that contains an array to grab the record. This is done …
> First fix for the XSSRays

- config.yaml
- core/main/handlers/hookedbrowsers.rb
Core Functionality
**Q:** _Please give a brief summary of your feature/fix_
**A:** Alternative PR to @icamys Added excluded_hooking_subnet config option (#1879). There was some logic that made the code a little difficult to interpret, and it did not look like the feedback was going to be addressed. I liked the feature, so made some small changes to make it slightly easier to read. 
**Q:** _Give a technical rundown of what you have changed (if applicable)_
**A:** BeEF currently has functionality to target and only hook a specified set of subnets. This feature is similar in nature, but instead allows a user to specify a set of subnets that they wish to prevent from ever being hooked.
**Q:** _Describe your test cases, what you have covered and if there are any use cases that still need …
> Excluded hooking subnet

- extensions/proxy/proxy.rb
Bug
**A:** Proxied requests with query string params (e.g. https://foo.example/bar?fizz=buzz) were being sent without the query string (i.e. https://foo.example/bar)
**A:** If the `URI` has a `query` then construct a path that includes the query string
**A:**
No test cases written. I've done simple testing in the lab only. I'd appreciate a careful look and further testing.
:heavy_check_mark: Proxied requests without a query string work, and are sent without a query string
:heavy_check_mark: Proxied requests with a query string (`?foo`) work, and are …
> Include URI query string in proxied requests

- Gemfile
```
Name: nokogiri
Version: 1.10.10
Advisory: CVE-2020-26247
Criticality: Low
URL: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vr8q-g5c7-m54m
Title: Nokogiri::XML::Schema trusts input by default, exposing risk of an XXE vulnerability
Solution: upgrade to >= 1.11.0.rc4
Vulnerabilities found!
```
I'm not sure if BeEF is affected by this but it makes sense to enforce use of a newer and non-vulnerable version.
> Gemfile: Bump nokogiri version from >= 1.10.8 to >= 1.11.1

- .rubocop.yml
Ruby 2.5 will be EOL in less than two months.
> Rubocop: Bump Ruby version to 2.6 and define new cops

- modules/social_engineering/gmail_phishing/command.js
Module
**Q:** Gmail Phishing automatically led to https://accounts.google.com/ServiceLogin which is returns a 404 not found error
**A:** I basically changed it to https://accounts.google.com/, it no longer returns a 404 error and the target should not be suspicious...
> Fixed Gmail Phishing by updating https://accounts.google.com/ServiceLogin to https://accounts.google.com/

- extensions/social_engineering/models/web_cloner.rb
- extensions/social_engineering/web_cloner/web_cloner.rb
- spec/beef/extensions/social_engineering_spec.rb
changed WebCloner name changes in web_cloner.rb
created two tests to support changeswq
Extension Defect
Issue with persistence of a cloned web site.
Model was not named inline with ActiveRecord syntax and therefore the table could not be found.
Create a basic model create test, improvement required would be to add a checking expect
Created a test of the entire web cloning functionality, there is an improvement of using the beef auth page instead off google.com
> renamed the WebCloner model class to align with ActiveRecord syntax

- Gemfile
- beef
- spec/beef/api/auth_rate_spec.rb
- spec/beef/core/main/autorun_engine/autorun_engine_spec.rb
- spec/beef/extensions/requester_spec.rb
- spec/beef/extensions/websocket_hooked_browser_spec.rb
- spec/beef/modules/debug/test_beef_debugs_spec.rb
- spec/spec_helper.rb
Core Functionality / Gem compatibility fix -  Database connection
**A:** As per OTR-ActiveRecord 2.0.0 they require you to manually establish the database connection which means that the latest gem versions has not been usable. I have added the manual call and also a check to confirm that the version is 2.0.0 or higher as it will bug out on older gem versions. This also includes on the spec files when they are called and should handle.
Relates to:
#2093 #2115 
**A:** The OTR-ActiveRecord gem requires you to call ``` OTR::ActiveRecord.establish_connection!  ``` when you establish the …
> OTR-ActiveRecord update: added to manually call the database connection

- spec/beef/extensions/social_engineering_spec.rb
Bug, Tests
As ssen in #2149 there was an bug in the spec social_engerieering_spec.rb
To prevent this bug the BeEF::Core::Server.instance.prepare can be used to prevent @rack_app from being nil allowing the testing to execute and pass
> Testing: Error running social_engerring_spec

- extensions/admin_ui/media/javascript/ui/panel/zombiesTreeList.js
Extension: Admin UI
Currently there is a defect if an offline zombie exists and you try to delete it in the tree list view, it will not delete.
This was due to the existing code not referencing the correct variable for online/offline hooked browser
```Javascript
var hb_id = this.contextNode.id.split('zombie-online-')[1];
var hb_id_off = this.contextNode.id.split('zombie-offline-')[1];
```
The code used to delete the zombie referenced the hb_id
```Javascript
var token = beefwui.get_rest_token();
if (!confirm('Are you sure you want to delete zombie [id: ' + hb_id + '] ?\nWarning: this will remove all zombie related data, including logs and command results!')) {
//commands_statusbar.update_fail('Cancelled');
return;
}
//commands_statusbar.update_sending('Removing zombie [id: ' + hb_id + '] …
```
> Extension: AdminUI: Fixed offline zombie not deleting

- beef
- core/main/console/commandline.rb
> Usability: #2145. Added user input request for beef update within 'beef' install script

- config.yaml
- extensions/admin_ui/media/javascript/ui/panel/PanelViewer.js
Bug
**Q:** _Please give a brief summary of your feature/fix_
**A:** The current release of BeEF master contains a bug in the 'Current Browser' zombie commands status bar. Any request made or command module launched resulted in an error similar to that highlighted in the picture below:
This patch resolves this issue.
**Q:** _Give a technical rundown of what you have changed (if applicable)_
**A:** The data previously passed into the constructor which generates these messages was only being given an object `zombie` which contained the one key `session` whose value was the Session ID for that hooked browser. The status bar was trying to call on …
> Fix #1851 - Command/request(s) sent to zombie 'undefined' bug

- modules/browser/hooked_domain/apache_tomcat_examples_cookie_disclosure/command.js
- modules/browser/hooked_domain/apache_tomcat_examples_cookie_disclosure/config.yaml
- modules/browser/hooked_domain/apache_tomcat_examples_cookie_disclosure/module.rb
Apache Tomcat RequestHeaderExample Cookie Disclosure module.
I still encounter Apache Tomcat with the `examples` app deployed from time to time. The examples include a `RequestHeaderExample` servlet which returns request headers in the HTTP response body, including all cookies. This offers a trivial method to bypass `HttpOnly` protection on cookies. This is an old and well known technique that has existed for at least 5 years (likely much longer).
1. Install Apache Tomcat. I used bitnami: https://bitnami.com/stack/tomcat/virtual-machine
2. Ensure the `examples` application is installed and deployed.
3. Browse to a page on the server which issues cookies. Most of the JSP examples at `/examples/jsp/` (such as `/examples/jsp/jsp2/simpletag/hello.jsp`) will generate cookies (with `HttpOnly`). …
> Modules: Add apache_tomcat_examples_cookie_disclosure module

- beef
https://github.com/beefproject/beef/blob/66257f1cf3a5d99acdd9e1ad94cc1637853549ad/beef#L60
When executing docker run as per instructions, it would fail on response being nil.
I have added a nil guard to prevent error
> Defect: user input in beef script no longer causes docker to error when building and running beef

- install
From #2249 Line 93 of install script now includes `grep -v "IMAGE"` to filter out the extra line which may appear.
```
DISTRO_ID=$(cat /etc/os-release | grep  ID= | grep -v "BUILD" | grep -v "IMAGE" | cut -d= -f2-)
```
From: https://www.freedesktop.org/software/systemd/man/os-release.html
IMAGE_ID=
A lower-case string (no spaces or other characters outside of 0–9, a–z, ".", "_" and "-"), identifying a specific image of the operating system. This is supposed to be used for environments where OS images are prepared, built, shipped and updated as comprehensive, consistent OS images. This field is optional and may not be implemented on all systems, in particularly not on those that are not managed via images but put together and updated from individual packages and on the local system. …
> #2249 Added additional grep command to correctly identify arch distro

- modules/exploits/beefbind/shellcode_sources/msf/beef_bind-handler.rb
- modules/exploits/beefbind/shellcode_sources/msf/beef_bind-stage-linux-x86.rb
- modules/exploits/beefbind/shellcode_sources/msf/beef_bind-stager-linux-x64.rb
- modules/exploits/beefbind/shellcode_sources/msf/beef_bind-stager-linux-x86.rb
- modules/exploits/beefbind/shellcode_sources/msf/beef_bind-stager-windows-x86.rb
Bug
**A:**  I have adapted the bind_shell modules for metasploit version 6.1.10-dev.
**A:** Module names have been changed, as metasploit did not recognise the module with capital letters in the name.
**A:**I started metasploit and msfvenom and it was already detecting the cases. Previously it gave an error and no module was started.
> Fix modules for Metasploit v6.1.10-dev

- core/api.rb
> core/api: Fix typo for undefined variable 'method'

- .rubocop.yml
BeEF uses Ruby 2.7. Ruby 2.6 is no longer supported.
Enable `NewCops` for now. If it is a problem we can disable it in the future. However, if any new rules are problematic, we should simply explicitly disable them instead.
> Rubocop: Update TargetRubyVersion to 2.7 and enable all NewCops

- INSTALL.txt
- README.md
- beef
Ruby 2.5 is end of life.
We've already described Ruby 2.7 as the minimum version elsewhere in the code base.
> Bump minimum required Ruby version from 2.5 to 2.7

- core/main/configuration.rb
Fixes #2333
```
[ 7:37:03][!] Fatal Error: cannot load configuration file '/root/Desktop/beef/./config.yaml' : uninitialized class variable @@instance in BeEF::Core::Configuration
Did you mean?  instance_of?
[ 7:37:03][!] ["/root/Desktop/beef/core/main/configuration.rb:16:in `instance'", "/root/Desktop/beef/core/ruby/print.rb:38:in `print_debug'", "/root/Desktop/beef/core/main/configuration.rb:49:in `rescue in load'", "/root/Desktop/beef/core/main/configuration.rb:43:in `load'", "/root/Desktop/beef/core/main/configuration.rb:28:in `initialize'", "./beef:83:in `new'", "./beef:83:in `<main>'"]
Traceback (most recent call last):
4: from ./beef:91:in `<main>'
3: from /root/Desktop/beef/core/main/configuration.rb:201:in `get'
2: from /root/Desktop/beef/core/main/configuration.rb:201:in …
```
> Treat core configuration file load failure as fatal

- beef
It seems unlikely that users would need/want to use BeEF with a read only database. Easier to simply exit.
> Exit upon database connection errors at startup

- modules/misc/ibm_inotes/extract_inotes_list/command.js
- modules/misc/ibm_inotes/extract_inotes_list/module.rb
- modules/misc/ibm_inotes/inotes_flooder/command.js
- modules/misc/ibm_inotes/inotes_flooder/module.rb
- modules/misc/ibm_inotes/read_inotes/command.js
- modules/misc/ibm_inotes/read_inotes/module.rb
- modules/misc/ibm_inotes/send_inotes/command.js
- modules/misc/ibm_inotes/send_inotes/module.rb
- modules/misc/ibm_inotes/send_inotes_with_attachment/command.js
- modules/misc/ibm_inotes/send_inotes_with_attachment/module.rb
Bug fix
As per #2364 https://github.com/beefproject/beef/issues/2364 there was a spelling mistake within the IBM inotes modules which caused it to fail. Additionally there was no handling where the module could not find the target nsf url.
1. Fixed spelling mistake per Bcoles suggestions in #2364 
2. Added 'name' to the `options` object for each module as per Bcoles suggestions
3. Added a bandaid try/catch to the function so that it does not error but fails and returns the error to the UI. While the module  group should ideally be rewritten to handle fails better, this at least allows it to be run without crashing
No rspec tests written, but …
> 2364 inotes modules defect and error handling

- extensions/requester/rest/requester.rb
Bug
Previously `requester` extension has not worked correctly. It has really initiated sending the request by Browser, and correctly saved the result to DB. But it did not showed the result in web panel: `Response Body` was empty.
The bug caused by impropper `if `statement and introduced in commit https://github.com/beefproject/beef/commit/aa7a6f9e644ef8da9006a28379f0193df00dba99
This is the first time I am using ruby. So, please, make sure I did everything right.
> Fixed bug when response_data is empty when http.response_data.length is <= 100K

- extensions/webrtc/api/hook.rb
- extensions/webrtc/handlers.rb
- extensions/webrtc/models/rtcmanage.rb
- extensions/webrtc/models/rtcsignal.rb
- extensions/webrtc/rest/webrtc.rb
> WebRTC: Rename Rtc model classes to align with ActiveRecord syntax

- install
Extension to installer (Core Functionality?)
Added support for SuSE derivatives (such as opensuse etc) in the install script
The install script uses zypper to install needed packages after checking if they are already there (if they are, the install is skipped). Because Opensuse has multiple versions of nodejs, it installs nodejs16 since that is more likely to be there on the other (older) distros, but it allows nodejs18 to satisfy it if it is already installed.
Tested on OpenSuSE Tumbeweed version 20220930
> Add support for the SuSE family in the installer

- Rakefile
- beef
- extensions/console/lib/rbreadline.rb
- extensions/console/lib/sedTmoz0z
- spec/beef/api/auth_rate_spec.rb
- tools/chrome_extensions_exploitation/webstore_uploader/webstore_upload.rb
`File.exists?` was deprecated in Ruby 2.1.0 and has been removed in the Ruby 3.2.0.
* https://bugs.ruby-lang.org/issues/17391
* https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/
> Replace deprecated File.exists? with File.exist?

- arerules/alert.json
- arerules/coinhive_miner.json
- arerules/confirm_close_tab.json
- arerules/ff_osx_extension-dropper.json
- arerules/get_cookie.json
- arerules/ie_win_htapowershell.json
- arerules/lan_cors_scan.json
- arerules/lan_cors_scan_common.json
- arerules/lan_fingerprint.json
- arerules/lan_fingerprint_common.json
- arerules/lan_flash_scan.json
- arerules/lan_flash_scan_common.json
- arerules/lan_http_scan.json
- arerules/lan_http_scan_common.json
- arerules/lan_ping_sweep.json
- arerules/lan_ping_sweep_common.json
- arerules/lan_port_scan.json
- arerules/lan_sw_port_scan.json
- arerules/man_in_the_browser.json
- arerules/raw_javascript.json
- arerules/record_snapshots.json
- arerules/win_fake_malware.json
- core/main/autorun_engine/engine.rb
- core/main/handlers/browserdetails.rb
- core/main/models/legacybrowseruseragents.rb
- core/main/network_stack/websocket/websocket.rb
- core/main/rest/handlers/autorun_engine.rb
- tools/rest_api_examples/autorun
- tools/rest_api_examples/lib/beef_rest_api.rb
Replace `BeEF::Core::AutorunEngine::Models` with `BeEF::Core::Models`. Fixes #2019. Shoutout to @Squigilum for fixing this in #2020 which was unfortunately never merged.
---
Rename the REST API URL routes to be more sensible. Request all rules with `/api/autorun/rules`. No more of this `/api/autorun/rule/list/all` nonsense.
```
get '/rules'
get '/rule/:rule_id'
get '/run/:rule_id'
get '/run/:rule_id/:hb_id'
post '/rule/add'
delete '/rule/:rule_id'
```
---
Add REST API samples for the Autorun REST API.
---
Massive refactor of the Autorun Engine. It is still terrible but now the code is readable.
---
Remove `os` / `browser` properties with redundant 'ALL' values from sample ARE rules. `ALL` is implied and does not need to be defined.
> AutorunEngine: Cleanup, rename REST routes, use Core::Models in REST API

- config.yaml
- core/main/client/browser.js
- core/main/handlers/browserdetails.rb
- core/main/handlers/modules/beefjs.rb
- core/main/handlers/modules/legacybeefjs.rb
- core/main/handlers/modules/multistagebeefjs.rb
- core/main/rest/handlers/hookedbrowsers.rb
- docs/browser.js.html
- spec/support/assets/config_new.yaml
- spec/support/assets/config_old.yaml
PhishingFrenzy appears to be a dead project. The website is down and the repository has not been updated in 5+ years.
The integration was originally added by a PhishingFrenzy developer and consists of two parts:
* Rather than PhishingFrenzy using BeEF's APIs, REST API calls were added specifically for use by PhishingFrenzy. These API calls are not used anywhere else and add additional maintenance burden.
* Additional code was added to the browser hook to grab the PhishingFrenzy session ID from `window.location.search` and store it in the database. If hte PhishingFrenzy project is still alive and wants to continue integrating with BeEF, you can grab the ID from the `browser.window.url` property from the `BrowserDetails` model in the database via the REST API.
> Remove PhishingFrenzy integration

- Rakefile
- generate-certificate
- scripts/bump-version.sh
The `generate-certificate` script is not required as certificate generation is performed by Rake tasks:
```
rake ssl:create                 # Create a new SSL certificate
rake ssl:replace                # Re-generate SSL certificate
```
Unfortunately users will need to install test dependencies to run Rake tasks via Rake. I don't care.
> Scripts: Remove CDE Rake task and generate-certificate script

- core/main/client/updater.js
- core/main/client/websocket.js
- core/main/network_stack/websocket/websocket.rb
- extensions/events/api.rb
- extensions/events/extension.rb
- extensions/events/handler.rb
Fixes #1570.
This isn't ideal, but it will do for now. The entire WebSocket command and control functionality requires review.
> WebSockets: flush beef.net.queue during keepalive

- extensions/notifications/channels/slack_workspace.rb
Fixes #2819.
I broke the Slack WebHook validation conditional logic when converting the regex check to a string comparison check in aa7a6f9e644ef8da9006a28379f0193df00dba99 (removed `s` character instead of `\` character).
> Notifications: Slack: Fix config file WebHook validation

- INSTALL.txt
- beef
Confirmed Development is Alive: [REF #2982](https://github.com/beefproject/beef/pull/2982) `Update README.md "Ruby Version 3.0+"`
As per:
https://github.com/beefproject/beef/blob/554d42b2c61e5e296d89a50f607031131a56a007/install#L186
Documents behind:
https://github.com/beefproject/beef/blob/554d42b2c61e5e296d89a50f607031131a56a007/INSTALL.txt#L24-L26
https://github.com/beefproject/beef/blob/554d42b2c61e5e296d89a50f607031131a56a007/beef#L15-L17
GitHub Pages deployment seems to be stuck on 2.5?
https://beefproject.github.io/beef/
> Update Ruby Version - Complete

- extensions/notifications/channels/ntfy.rb
- extensions/notifications/config.yaml
- extensions/notifications/notifications.rb
Extension
**A:** Adds the option to use ntfy as a notifier
**A:** 
I added the following:
**New Module**: Introduced a new notification module under `BeEF::Extension::Notifications::Channels` named **Ntfy**. This module allows BeEF to send notifications through the ntfy platform.
**URI Parsing**: Utilized the URI library to accurately parse the endpoint URL configured in the settings.
**HTTP Basic Authentication**: Implemented HTTP Basic Authentication support for the ntfy endpoint. The username and password are fetched from the configuration and, if present, are used to set the …
> Add ntfy extension

- modules/browser/hooked_domain/cisco_asa_password_disclosure/command.js
- modules/browser/hooked_domain/cisco_asa_password_disclosure/config.yaml
- modules/browser/hooked_domain/cisco_asa_password_disclosure/module.rb
Adds a plaintext credential recovery for Cisco ASA WebVPN. Cisco has told me that this isn't a vulnerability & they will not be patching it, which means you will be able to do this in perpetuity. So get your hooks onto an ASA, if/when the user logs in, or is already logged into a target ASA, you can recover their plaintext credentials for that particular session. This may open up future pivoting.
Also, shout out to the use of ROT13 by a multi-billion dollar company to do... something?
Based on: https://github.com/catatonicprime/CVE-2020-3580
Module
**A:** Noticed that Cisco ASA's let you recovery ROT13 versions of the current session's password. And they have known XSS vulns (CVE-2020-3580). Match made in heaven. 
**Q:** Give a …
> Cisco ASA Plaintext Password Recovery

- .github/workflows/github_actions.yml
- Gemfile
- Gemfile.lock
- beef
- package-lock.json
- package.json
- spec/beef/core/main/autorun_engine/autorun_engine_spec.rb
- spec/beef/core/main/handlers/browser_details_handler_spec.rb
- spec/beef/extensions/requester_spec.rb
- spec/beef/extensions/websocket_hooked_browser_spec.rb
- spec/beef/modules/debug/test_beef_debugs_spec.rb
- spec/spec_helper.rb
Bug
**A:** Upgrade activerecord to 7.2 and refactor code for new version
**A:** Fix activerecord migration code to be compatible with the new version and upgrade the version of activerecord
**A:** bundle exec rake, debug modules, browserstack tests.
> Upgrade activerecord to 7.2 and refactor code for new version
